test_field_bperp_iter – QuickPIC wit Azimuzal Decomposition
test_field_bperp_iter Program
105 statements
Source File
Uses
field_b_class
field_class
field_src_class
system
param
mpi
ufield_class
debug_tool
Calls
Contents
Variables
b jay djdxi num_modes dim part_shape nd nvp gc_num dr dxi r ujay_re ujay_im udjdxi_re udjdxi_im ub_re_new ub_im_new ub_re_old ub_im_old ub_res p ierr i mode iter num_iter res
Variables
Type Attributes Name Initial
type(field_b) :: b
type(field_jay) :: jay
type(field_djdxi) :: djdxi
integer :: num_modes = 2
integer :: dim = 3
integer :: part_shape = p_ps_linear
integer, dimension(2) :: nd = (/128, 1/)
integer, dimension(2) :: nvp = (/1, 1/)
integer, dimension(2,2) :: gc_num
real :: dr
real :: dxi
real :: r
type(ufield), dimension(:), pointer :: ujay_re => null()
type(ufield), dimension(:), pointer :: ujay_im => null()
type(ufield), dimension(:), pointer :: udjdxi_re => null()
type(ufield), dimension(:), pointer :: udjdxi_im => null()
type(ufield), dimension(:), pointer :: ub_re_new => null()
type(ufield), dimension(:), pointer :: ub_im_new => null()
type(ufield), dimension(:), pointer :: ub_re_old => null()
type(ufield), dimension(:), pointer :: ub_im_old => null()
type(ufield) :: ub_res
real, dimension(:,:), pointer :: p
integer :: ierr
integer :: i
integer :: mode
integer :: iter
integer :: num_iter = 10
real, dimension(:,:), pointer :: res => null()
Call graph
test_field_bperp_iter calls mpi_init, write_dbg, mpi_finalize, init_errors, end_errors