test_field_eperp – QuickPIC wit Azimuzal Decomposition
test_field_eperp Program
140 statements
Source File
Uses
field_b_class
field_e_class
field_psi_class
field_class
field_src_class
system
param
mpi
ufield_class
debug_tool
Calls
Contents
Variables
b e psi rho jay djdxi num_modes dim order part_shape nd nvp gc_num dr dxi r uq_re uq_im ue_re ue_im ujay_re ujay_im udjdxi_re udjdxi_im ub_re ub_im upsi_re upsi_im p ierr i mode
Variables
Type Attributes Name Initial
type(field_b) :: b
type(field_e) :: e
type(field_psi) :: psi
type(field_rho) :: rho
type(field_jay) :: jay
type(field_djdxi) :: djdxi
integer :: num_modes = 3
integer :: dim = 3
integer :: order = p_fs_2order
integer :: part_shape = p_ps_linear
integer, dimension(2) :: nd = (/128, 1/)
integer, dimension(2) :: nvp = (/1, 1/)
integer, dimension(2,2) :: gc_num
real :: dr
real :: dxi
real :: r
type(ufield), dimension(:), pointer :: uq_re => null()
type(ufield), dimension(:), pointer :: uq_im => null()
type(ufield), dimension(:), pointer :: ue_re => null()
type(ufield), dimension(:), pointer :: ue_im => null()
type(ufield), dimension(:), pointer :: ujay_re => null()
type(ufield), dimension(:), pointer :: ujay_im => null()
type(ufield), dimension(:), pointer :: udjdxi_re => null()
type(ufield), dimension(:), pointer :: udjdxi_im => null()
type(ufield), dimension(:), pointer :: ub_re => null()
type(ufield), dimension(:), pointer :: ub_im => null()
type(ufield), dimension(:), pointer :: upsi_re => null()
type(ufield), dimension(:), pointer :: upsi_im => null()
real, dimension(:,:), pointer :: p
integer :: ierr
integer :: i
integer :: mode
Call graph
test_field_eperp calls mpi_init, write_dbg, mpi_finalize, init_errors, end_errors, write_data
write_data calls write_data1d, write_data2d, write_array