test_field_psi – QuickPIC wit Azimuzal Decomposition
test_field_psi Program
62 statements
Source File
Uses
field_psi_class
field_class
field_src_class
system
param
mpi
ufield_class
debug_tool
Calls
Contents
Variables
psi q num_modes dim order part_shape nd nvp gc_num dr dxi r uq_re uq_im upsi_re upsi_im p ierr i mode values
Variables
Type Attributes Name Initial
type(field_psi) :: psi
type(field_rho) :: q
integer :: num_modes = 2
integer :: dim = 1
integer :: order = p_fs_2order
integer :: part_shape = p_ps_linear
integer, dimension(2) :: nd = (/128, 1/)
integer, dimension(2) :: nvp = (/1, 1/)
integer, dimension(2,2) :: gc_num
real :: dr
real :: dxi
real :: r
type(ufield), dimension(:), pointer :: uq_re => null()
type(ufield), dimension(:), pointer :: uq_im => null()
type(ufield), dimension(:), pointer :: upsi_re => null()
type(ufield), dimension(:), pointer :: upsi_im => null()
real, dimension(:,:), pointer :: p
integer :: ierr
integer :: i
integer :: mode
real, dimension(1024) :: values = 0.0
Call graph
test_field_psi calls mpi_init, write_dbg, mpi_finalize, init_errors, end_errors, write_data
write_data calls write_data1d, write_data2d, write_array