end_field_solver – QuickPIC wit Azimuzal Decomposition
end_field_solver Subroutine
35 statements
Source File
private subroutine end_field_solver(this)
Arguments
Type Intent Optional Attributes Name
class(field_solver), intent(inout) :: this
Calls
Contents
None
Call graph
end_field_solver calls hypre_structgmresdestroy, hypre_structsmgdestroy, hypre_structgriddestroy, hypre_structvectordestroy, hypre_ijmatrixdestroy, hypre_structpcgdestroy, hypre_structcycreddestroy, hypre_structjacobidestroy, write_dbg, hypre_structstencildestroy, hypre_structmatrixdestroy, hypre_boomeramgdestroy, hypre_ijvectordestroy