init_field_solver – QuickPIC wit Azimuzal Decomposition
init_field_solver Subroutine
36 statements
Source File
private subroutine init_field_solver(this, nd, ndp, noff, kind, mode, dr, solver_type, tol)
Arguments
Type Intent Optional Attributes Name
class(field_solver), intent(inout) :: this
integer, intent(in), dimension(2) :: nd
integer, intent(in), dimension(2) :: ndp
integer, intent(in), dimension(2) :: noff
integer, intent(in) :: kind
integer, intent(in) :: mode
real, intent(in) :: dr
integer, intent(in) :: solver_type
real, intent(in) :: tol
Calls
Contents
None
Call graph
init_field_solver calls hypre_ijvectorsetobjecttype, write_dbg, hypre_structvectorcreate, hypre_structvectorinitialize, hypre_ijvectorcreate, hypre_ijvectorinitialize