set_struct_solver – QuickPIC wit Azimuzal Decomposition
set_struct_solver Subroutine
57 statements
Source File
private subroutine set_struct_solver(this, comm)
Arguments
Type Intent Optional Attributes Name
class(field_solver), intent(inout) :: this
integer, intent(in) :: comm
Calls
Contents
None
Call graph
set_struct_solver calls hypre_structsmgsetprintlevel, hypre_structgmressettol, hypre_structcycredsetup, write_dbg, hypre_structpcgsetrelchange, hypre_structgmressetprintlevel, hypre_structpcgcreate, hypre_structjacobisetzeroguess, hypre_structgmressetlogging, hypre_structjacobisetmaxiter, hypre_structsmgsetlogging, hypre_structgmressetup, hypre_structpcgsetprecond, hypre_structcycredcreate, hypre_structsmgsetnumprerelax, hypre_structpcgsetlogging, hypre_structjacobisettol, hypre_structpcgsetmaxiter, hypre_structsmgsettol, hypre_structpcgsetprintlevel, hypre_structpcgsettwonorm, hypre_structsmgsetnumpostrelax, hypre_structsmgcreate, hypre_structsmgsetrelchange, hypre_structgmressetmaxiter, hypre_structpcgsetup, hypre_structgmressetprecond, hypre_structpcgsettol, hypre_structjacobicreate, hypre_structsmgsetmemoryuse, hypre_structsmgsetup, hypre_structsmgsetmaxiter, hypre_structgmrescreate