set_struct_grid – QuickPIC wit Azimuzal Decomposition
set_struct_grid Subroutine
15 statements
Source File
private subroutine set_struct_grid(this, comm, ndp, noff)
Arguments
Type Intent Optional Attributes Name
class(field_solver), intent(inout) :: this
integer, intent(in) :: comm
integer, intent(in), dimension(2) :: ndp
integer, intent(in), dimension(2) :: noff
Calls
Contents
None
Call graph
set_struct_grid calls hypre_structgridsetextents, hypre_structgridcreate, hypre_structgridassemble, write_dbg