set_ij_solver – QuickPIC wit Azimuzal Decomposition
set_ij_solver Subroutine
47 statements
Source File
private subroutine set_ij_solver(this, comm)
Arguments
Type Intent Optional Attributes Name
class(field_solver), intent(inout) :: this
integer, intent(in) :: comm
Calls
Contents
None
Call graph
set_ij_solver calls hypre_structsmgsetprintlevel, hypre_parcsrpcgcreate, hypre_parcsrpcgsettol, hypre_boomeramgsetcoarsentype, write_dbg, hypre_boomeramgsetmaxlevels, hypre_parcsrpcgsettwonorm, hypre_structsmgsetlogging, hypre_boomeramgsettol, hypre_boomeramgsetmaxiter, hypre_structsmgsetnumprerelax, hypre_boomeramgcreate, hypre_structsmgsettol, hypre_structsmgcreate, hypre_structsmgsetnumpostrelax, hypre_structsmgsetrelchange, hypre_boomeramgsetrelaxtype, hypre_boomeramgsetnumsweeps, hypre_parcsrpcgsetprecond, hypre_parcsrpcgsetup, hypre_structsmgsetmemoryuse, hypre_boomeramgsetup, hypre_boomeramgsetrelaxorder, hypre_structsmgsetup, hypre_parcsrpcgsetmaxiter, hypre_structsmgsetmaxiter