set_ij_matrix – QuickPIC wit Azimuzal Decomposition
set_ij_matrix Subroutine
90 statements
Source File
private subroutine set_ij_matrix(this, comm, nd, ndp, noff, dr)
Arguments
Type Intent Optional Attributes Name
class(field_solver), intent(inout) :: this
integer, intent(in) :: comm
integer, intent(in), dimension(:) :: nd
integer, intent(in), dimension(:) :: ndp
integer, intent(in), dimension(:) :: noff
real, intent(in) :: dr
Calls
Contents
None
Call graph
set_ij_matrix calls hypre_ijmatrixsetobjecttype, hypre_ijmatrixgetobject, hypre_ijmatrixcreate, hypre_ijmatrixinitialize, write_dbg, hypre_ijmatrixassemble, hypre_ijmatrixsetvalues