solve_equation – QuickPIC wit Azimuzal Decomposition
solve_equation Subroutine
45 statements
Source File
private subroutine solve_equation(this, src_sol)
Arguments
Type Intent Optional Attributes Name
class(field_solver), intent(inout) :: this
real, intent(inout), dimension(:), pointer :: src_sol
Calls
Contents
None
Call graph
solve_equation calls hypre_structvectorassemble, hypre_structsmgsolve, hypre_boomeramgsolve, hypre_structpcgsolve, write_dbg, hypre_ijvectorgetobject, hypre_structvectorgetboxvalues, hypre_ijvectorassemble, hypre_ijvectorgetvalues, hypre_structcycredsolve, hypre_structvectorsetboxvalues, hypre_ijvectorsetvalues, hypre_structgmressolve