write_data1d – QuickPIC wit Azimuzal Decomposition
write_data1d Subroutine
13 statements
Source File
public subroutine write_data1d(f, fname, dim)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:,:), pointer :: f
character(len=*), intent(in) :: fname
integer, intent(in) :: dim
Called by
Contents
None
Call graph
write_data calls write_data1d
test_field_eperp calls write_data
test_field_bz calls write_data
test_field_psi calls write_data
test_field_bperp calls write_data
test_field_ez calls write_data