#!/bin/python3
import glob
import os
import h5py
import numpy as np
import sys
import getopt


def get_max_mode():

    rr_dirs = glob.glob('Re_Re*')
    ir_dirs = glob.glob('Im_Re*')
    ri_dirs = glob.glob('Re_Im*')
    ii_dirs = glob.glob('Im_Im*')
    num_rr_dirs = 0
    num_ri_dirs = 0
    num_ir_dirs = 0
    num_ii_dirs = 0

    for obj in rr_dirs:
        if os.path.isdir(obj):
            num_rr_dirs += 1
    
    for obj in ri_dirs:
        if os.path.isdir(obj):
            num_ri_dirs += 1

    for obj in ir_dirs:
        if os.path.isdir(obj):
            num_ir_dirs += 1

    for obj in ii_dirs:
        if os.path.isdir(obj):
            num_ii_dirs += 1

    assert num_rr_dirs == num_ir_dirs, 'Wrong number of folders!'
    assert num_ri_dirs == num_ii_dirs, 'Wrong number of folders!'
    assert num_rr_dirs == num_ri_dirs + 1, 'Wrong number of folders!'
    assert num_ir_dirs == num_ii_dirs + 1, 'Wrong number of folders!'

    return num_rr_dirs - 1


def get_file_list():

    file_list = glob.glob('Re_Re0/*_*.h5')
    file_list = [os.path.basename(file) for file in file_list]
    return file_list


if __name__ == '__main__':

    # check input arguments
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'ha:', ['help', 'angle='])
    except getopt.GetoptError:
        print('Usage: postprocess_laser -a <angle in degree>')
        sys.exit(2)

    # read input arguments
    phi = 0
    phi_degree = 0
    for opt, arg in opts:
        if opt in ('-h', '--help'):
            print('Usage: postprocess_laser -a <angle in degree>')
        elif opt in ('-a', '--angle'):
            phi_degree = arg
            phi = float(arg) / 180 * np.pi

    max_mode = get_max_mode()
    file_list = get_file_list()
    num_files = len(file_list)

    # create the root folders for amplitude and phase
    if not os.path.exists('Amp_angle_' + str(phi_degree)):
        os.mkdir('Amp_angle_' + str(phi_degree))
    if not os.path.exists('Pha_angle_' + str(phi_degree)):
        os.mkdir('Pha_angle_' + str(phi_degree))

    # read hdf5 properties
    filename = 'Re_Re0/' + file_list[0]
    with h5py.File(filename, 'r') as h5file:

        # read dataset name and attributes
        dset_name = list(h5file.keys())[1]
        h5dset = h5file[dset_name]
        dset_attrs = {name: value for name, value in h5dset.attrs.items()}
        dset_size = h5dset.shape

        # read axes and their attributes
        h5axis1 = h5file['AXIS']['AXIS1']
        h5axis2 = h5file['AXIS']['AXIS2']
        axis1 = np.array(h5axis1)
        axis2 = np.array(h5axis2)
        axis1[0] = -axis1[1]
        axis1_attrs = {name: value for name, value in h5axis1.attrs.items()}
        axis2_attrs = {name: value for name, value in h5axis2.attrs.items()}

    for filename in file_list:

        print('Merging file ' + filename + '...')

        # initialize merged dataset
        merged_dset_re = np.zeros((dset_size[0], dset_size[1] * 2 - 1))
        merged_dset_im = np.zeros((dset_size[0], dset_size[1] * 2 - 1))

        # add m = 0 mode to the merged dataset
        with h5py.File('Re_Re0/' + filename, 'r') as h5file:

            # read file attributes
            file_attrs = {name: value for name, value in h5file.attrs.items()}

            dset = np.array(h5file[dset_name])
            merged_dset_re[:, 0:dset_size[1] - 1] += np.fliplr(dset[:, 1:])
            merged_dset_re[:, dset_size[1] - 1:] += dset

        with h5py.File('Im_Re0/' + filename, 'r') as h5file:

            # read file attributes
            file_attrs = {name: value for name, value in h5file.attrs.items()}

            dset = np.array(h5file[dset_name])
            merged_dset_im[:, 0:dset_size[1] - 1] += np.fliplr(dset[:, 1:])
            merged_dset_im[:, dset_size[1] - 1:] += dset

        # add m > 0 modes to the merged dataset
        for mode in np.arange(1, max_mode + 1):

            with h5py.File('Re_Re' + str(mode) + '/' + filename, 'r') as h5file:
                dset = np.array(h5file[dset_name])
                merged_dset_re[:, 0:dset_size[1] - 1] += np.fliplr(dset[:, 1:]) * 2 * np.cos(mode * (phi + np.pi))
                merged_dset_re[:, dset_size[1] - 1:] += dset * 2 * np.cos(mode * phi)

            with h5py.File('Re_Im' + str(mode) + '/' + filename, 'r') as h5file:
                dset = np.array(h5file[dset_name])
                merged_dset_re[:, 0:dset_size[1] - 1] -= np.fliplr(dset[:, 1:]) * 2 * np.sin(mode * (phi + np.pi))
                merged_dset_re[:, dset_size[1] - 1:] -= dset * 2 * np.sin(mode * phi)

            with h5py.File('Im_Re' + str(mode) + '/' + filename, 'r') as h5file:
                dset = np.array(h5file[dset_name])
                merged_dset_im[:, 0:dset_size[1] - 1] += np.fliplr(dset[:, 1:]) * 2 * np.cos(mode * (phi + np.pi))
                merged_dset_im[:, dset_size[1] - 1:] += dset * 2 * np.cos(mode * phi)

            with h5py.File('Im_Im' + str(mode) + '/' + filename, 'r') as h5file:
                dset = np.array(h5file[dset_name])
                merged_dset_im[:, 0:dset_size[1] - 1] -= np.fliplr(dset[:, 1:]) * 2 * np.sin(mode * (phi + np.pi))
                merged_dset_im[:, dset_size[1] - 1:] -= dset * 2 * np.sin(mode * phi)

        # calculate the amplitude and phase
        amp_dset = np.sqrt(merged_dset_re**2 + merged_dset_im**2)
        pha_dset = np.arctan2(merged_dset_im, merged_dset_re)

        # write to the h5 files
        with h5py.File('Amp_angle_' + str(phi_degree) + '/' + filename, 'w') as h5file:

            # write file attributes
            for key, val in file_attrs.items():
                h5file.attrs[key] = val

            # create new dataset and write the attributes
            h5dset = h5file.create_dataset(dset_name, data=amp_dset, dtype='f8')
            for key, val in dset_attrs.items():
                h5dset.attrs[key] = val

            # create group for axis and write the informations
            h5axis = h5file.create_group('AXIS')
            h5axis1 = h5axis.create_dataset('AXIS1', data=axis1)
            h5axis2 = h5axis.create_dataset('AXIS2', data=axis2)
            for key, val in axis1_attrs.items():
                h5axis1.attrs[key] = val
            for key, val in axis2_attrs.items():
                h5axis2.attrs[key] = val

        with h5py.File('Pha_angle_' + str(phi_degree) + '/' + filename, 'w') as h5file:

            # write file attributes
            for key, val in file_attrs.items():
                h5file.attrs[key] = val

            # create new dataset and write the attributes
            h5dset = h5file.create_dataset(dset_name, data=pha_dset, dtype='f8')
            for key, val in dset_attrs.items():
                h5dset.attrs[key] = val

            # create group for axis and write the informations
            h5axis = h5file.create_group('AXIS')
            h5axis1 = h5axis.create_dataset('AXIS1', data=axis1)
            h5axis2 = h5axis.create_dataset('AXIS2', data=axis2)
            for key, val in axis1_attrs.items():
                h5axis1.attrs[key] = val
            for key, val in axis2_attrs.items():
                h5axis2.attrs[key] = val
